title: Cyberphysische Systeme
description: Workshop to build a pub/sub app via mosquitto broker and deploying it all to IBM Cloud
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
highlighter: rouge

exclude:
  - LICENSE
  - .vscode/
  - .venv
  - .gitignore